export const ActionTypes = {
    STUDENT_PAID: 'STUDENT_PAID',
    COMPLAINTS: 'COMPLAINTS',
    SAVE_HOSTEL: 'SAVE_HOSTEL',
    ADD_COURSE: 'ADD_COURSE',
    ADD_RESULT: 'ADD_RESULT',
    REGISTER_COURSES: 'REGISTER_COURSES',
    REGISTER_RESULTS: 'REGISTER_RESULTS',
    APPROVE_COURSES: 'APPROVE_COURSES',
    WELCOME: 'WELCOME',
    STUDENT_LOGIN: 'STUDENT_LOGIN',
    CREATE_NEW_USER: 'CREATE_NEW_USER',
    CREATE_NEW_LECTURER: 'CREATE_NEW_LECTURER',
    LECTURER_LOGIN: 'LECTURER_LOGIN',
    NOTIFICATION: 'NOTIFICATION',
    LOGOUT: 'LOGOUT',


    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    STUDENT_API_ENDPOINT_ID: 'STUDENT_API_ENDPOINT_ID',

    POST_STUDENT_DETAILS_START: 'POST_STUDENT_DETAILS_START',
    POST_STUDENT_DETAILS_SUCCESS: 'POST_STUDENT_DETAILS_SUCCESS',
    POST_STUDENT_DETAILS_FAILED: 'POST_STUDENT_DETAILS_FAILED',

    GET_STUDENT_DETAILS_START: 'GET_STUDENT_DETAILS_START',
    GET_STUDENT_DETAILS_SUCCESS: 'GET_STUDENT_DETAILS_SUCCESS',
    GET_STUDENT_DETAILS_FAILED: 'GET_STUDENT_DETAILS_FAILED',
}