export const actionTypes = {

    ORGANIZATION_REGISTER_START: 'ORGANIZATION_REGISTER_START',
    ORGANIZATION_REGISTER_SUCCESS: 'ORGANIZATION_REGISTER_SUCCESS',
    ORGANIZATION_REGISTER_FAILED: 'ORGANIZATION_REGISTER_FAILED',

    ORGANIZATION_TENDER_DETAIL: 'ORGANIZATION_TENDER_DETAIL',

    ORGANIZATION_SELECT_BIDDER: 'ORGANIZATION_SELECT_BIDDER',

    ORGANIZATION_PROFILE_PICTURE: 'ORGANIZATION_PROFILE_PICTURE',

    ORGANIZATION_LOGOUT: 'ORGANIZATION_LOGOUT',
    USER_INFO: 'USER_INFO',
}