export const actionTypes = {
    ORGANIZATION_LOGIN_START: 'ORGANIZATION_LOGIN_START',
    ORGANIZATION_LOGIN_SUCCESS: 'ORGANIZATION_LOGIN_SUCCESS',
    ORGANIZATION_LOGIN_FAILED: 'ORGANIZATION_LOGIN_FAILED',

    FETCH_ORGANIZATION_NOTIFICATION_START: 'FETCH_ORGANIZATION_NOTIFICATION_START',
    FETCH_ORGANIZATION_NOTIFICATION_SUCCESS: 'FETCH_ORGANIZATION_NOTIFICATION_SUCCESS',
    FETCH_ORGANIZATION_NOTIFICATION_FAILED: 'FETCH_ORGANIZATION_NOTIFICATION_FAILED',
}